### PR TITLE
v 2.2 MultiLanguage

### PR DESCRIPTION
**Pull request by ComandPromt**
Hello, I have improved the program. It is in several languages thanks to an api created by me, it has translation files and an additional file that saves the current language so that if the user changes language, the language is changed immediately without restarting the application, and in the next Start of the program opens with the previously selected language.

I have improved the option to drag and drop files

### CODE REVIEW

**Comment by demarbre1u** [comment]
Hello, thanks again for your work! 

I noticed an issue though. I dragged and dropped an image, and then clicked on the "Convert" button. Everything seems to work fine; but I get two alerts : one indicating that everything went well, and a second one on top of the first that looks like an error with the message "Ruta invalida".

Could you look into that? I tested it on MacOS, so maybe that's only an issue on Mac though

**Comment by demarbre1u** [comment]
I tried again on Windows, but I couldn't reproduce the error.

So the issue seems to only happen on Mac.

**Comment by ComandPromt** [comment]
Have you put the Languages folder in the same path as the jar file? The program accesses the Languages folder for the language. I tried it on Windows and on Linux. They work on both operating systems.
Try to pass files of the same type and the format has to be the same as the format of the files, either png or jpg.
I leave you the test program so you can test it.

https://github.com/ComandPromt/ImageSplitterAndMerge/releases/download/v2.2/Image.Splitter_v_2.zip

**Comment by ComandPromt** [comment]
> I tried again on Windows, but I couldn't reproduce the error.
> 
> So the issue seems to only happen on Mac.



> I tried again on Windows, but I couldn't reproduce the error.
> 
> So the issue seems to only happen on Mac.

Please, tell me what is the command to open a folder on Mac, since I don't have a Mac I can't test the application, just tell me the command and I put it so that the program works on Mac

public static void openFolder(String path) throws IOException {

if (path != null && !path.equals("") && !path.isEmpty()) {

try {

if (System.getProperty("os.name").contains("indows")) {

Runtime.getRuntime().exec("cmd /c C:\\Windows\\explorer.exe " + "\"" + path + "\"");

}

else {

Runtime.getRuntime().exec("xdg-open " + path);

}

}

catch (IOException e) {

alerts.message("Invalid path", 1, 20);

}

}

}

**Pull request closed without merging**
